# Aspectos importantes para tomar en cuenta

## Reglas de nomenclatura

* Palabras separadas por guiones bajos
* Sesible a mayúsculas
* No iniciar con números

## Funciones

In [1]:
# Redondeo
redondeo = round(3.14159, 2)
print(redondeo)  # Salida: 3.14

3.14


In [2]:
# Interpolación
nombre = "Ana"
print(f"Hola, {nombre}!")  # Salida: Hola, Ana!

Hola, Ana!


In [5]:
# Eliminar espacios
texto = "   Hola, Mundo!   "
texto_limpio = texto.strip()
print(f"'{texto_limpio}'")  # Salida: 'Hola, Mundo!'

'Hola, Mundo!'


In [1]:
# Valor máximo y mínimo
numeros = [3, 1, 4, 1, 5, 9]
maximo = max(numeros)
minimo = min(numeros)
print(f"Máximo: {maximo}, Mínimo: {minimo}")  # Salida: Máximo: 9, Mínimo: 1

Máximo: 9, Mínimo: 1


In [ ]:
# Numpy
import numpy as np
array = np.array([1, 2, 3])
array2 = np.array([2, 3, 4])
print(array*2)  # Salida: [2 4 6]
print(array+1)  # Salida: [2 3 4]
print(array + array2)  # Salida: [3 5 7]

# Cálculo del promedio
promedio = np.mean(array)
print(promedio)  # Salida: 2.0

# Sumar todo
suma_total = np.sum(array)

[2 4 6]
[2 3 4]
[3 5 7]
2.0
